version: '3'

services:
  api:
    environment:
      - APP_ENV=development
      - PORT=8888
    # Volumes only for dev, since itll be compiled for prod
    volumes:
      - ./api/app:/go/src/github.com/pipa/app
    ports:
      - 8888:8888
    build: './api'
  front:
    environment:
      - NODE_ENV=development
      - PORT=9999
    ports:
      - 9999:9999
    # Volumes only for dev, since itll be compiled for prod
    volumes:
      - ./front/:/webroot/default
    command: npm start
    build: './front'
